name: PTCoach
options:
  bundleIdPrefix: com.ptcoach
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  PTCoach:
    type: application
    platform: iOS
    sources:
      - PTCoach
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ptcoach.PTCoach
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: PTCoach/Info.plist
      SWIFT_VERSION: "5.0"
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: Vision.framework
      - sdk: CoreML.framework
      - sdk: SwiftUI.framework
      - sdk: UIKit.framework
      - sdk: Foundation.framework
      - sdk: CoreGraphics.framework
      - sdk: AudioToolbox.framework
      - sdk: CoreVideo.framework
      - sdk: CoreMedia.framework
    info:
      path: PTCoach/Info.plist
      properties:
        CFBundleDisplayName: PTCoach
        CFBundleIdentifier: com.ptcoach.PTCoach
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        NSCameraUsageDescription: "PTCoach needs camera access for pose detection and exercise tracking"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
  
  PTCoachUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PTCoachUITests
    dependencies:
      - target: PTCoach
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ptcoach.PTCoachUITests
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: PTCoachUITests/Info.plist
      SWIFT_VERSION: "5.0"
